version: '3.8'
services:
  app:
    image: "stagecodes/otr-api-staging:latest"
    ports:
      - "3700:80"
    env_file:
      - app.env
    depends_on:
      - db
      # - cache
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - db.env
    ports:
      - "5432:5432"
  # cache:
  #   image: redis:latest

volumes:
  db_data:
